name: jobfind
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  device_preview: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  google_fonts: ^2.3.2
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
#
#    - family: Mulish
#      fonts:
#        - asset: assets/fonts/Mulish-Black.ttf

